version: '3.8'

services:
  planner-auth-service:
    image: planner-auth
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      planner-auth-db:
        condition: service_started
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - AUTH_DB_CONNECTION_STRING=Host=${AUTH_DB_HOST};Port=5432;Database=${AUTH_DB_DATABASE};Username=${AUTH_DB_USERNAME};Password=${AUTH_DB_PASSWORD}
      - PASSWORD_HASH_KEY=${PASSWORD_HASH_KEY}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - HOST=${HOST}

      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - MAILRU_CLIENT_ID=${MAILRU_CLIENT_ID}
      - MAILRU_CLIENT_SECRET=${MAILRU_CLIENT_SECRET}
      - MAILRU_REDIRECT_URI=${MAILRU_REDIRECT_URI}

      - FILE_SERVER_URL=${FILE_SERVER_URL}

      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - RABBITMQ_PROFILE_IMAGE_QUEUE_NAME=${RABBITMQ_PROFILE_IMAGE_QUEUE_NAME}
      - RABBITMQ_MAIL_CREDENTIALS_QUEUE_NAME=${RABBITMQ_MAIL_CREDENTIALS_QUEUE_NAME}
      - RABBITMQ_CREATE_CHAT_QUEUE_NAME=${RABBITMQ_CREATE_CHAT_QUEUE_NAME}
      - RABBITMQ_INIT_CHAT_QUEUE_NAME=${RABBITMQ_INIT_CHAT_QUEUE_NAME}
    volumes:
      - data-protection-keys:/keys