version: '3.8'

services:
  planner-auth-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${AUTH_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - planner-auth-data:/var/lib/postgresql/data