version: '3.8'

services:
  planner-chat-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${CONTENT_DB_USERNAME}
      - POSTGRES_PASSWORD=${CONTENT_DB_PASSWORD}
      - POSTGRES_DB=${CONTENT_DB_DATABASE}
    ports:
      - "5436:5432"
    volumes:
      - planner-chat-data:/var/lib/postgresql/data