version: '3.8'

services:
  planner-chat-service:
    image: planner-chat-service
    restart: always
    ports:
      - "8090:80"
    depends_on:
      planner-chat-db:
        condition: service_started
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - CHAT_DB_CONNECTION_STRING=Host=${CHAT_DB_HOST};Port=5432;Database=${CHAT_DB_DATABASE};Username=${CHAT_DB_USERNAME};Password=${CHAT_DB_PASSWORD}
      - PASSWORD_HASH_KEY=${PASSWORD_HASH_KEY}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - HOST=${HOST}

      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - FILE_SERVER_URL=${FILE_SERVER_URL}
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_CREATE_TASK_CHAT_QUEUE_NAME=${RABBITMQ_CREATE_TASK_CHAT_QUEUE_NAME}
      - RABBITMQ_CREATE_TASK_CHAT_RESPONSE_QUEUE=${RABBITMQ_CREATE_TASK_CHAT_RESPONSE_QUEUE}
      - RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE=${RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE}

      - RABBITMQ_CHAT_IMAGE_QUEUE_NAME=${RABBITMQ_CHAT_IMAGE_QUEUE_NAME}
      - RABBITMQ_CHAT_ATTACHMENT_QUEUE_NAME=${RABBITMQ_CHAT_ATTACHMENT_QUEUE_NAME}
      - RABBITMQ_CREATE_CHAT_QUEUE_NAME=${RABBITMQ_CREATE_CHAT_QUEUE_NAME}
      - RABBITMQ_INIT_CHAT_QUEUE_NAME=${RABBITMQ_INIT_CHAT_QUEUE_NAME}
      - RABBITMQ_CHAT_ADD_ACCOUNTS_TO_TASK_CHATS_QUEUE_NAME=${RABBITMQ_CHAT_ADD_ACCOUNTS_TO_TASK_CHATS_QUEUE_NAME}