version: '3.8'

services:
  planner-chat-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${CHAT_DB_USERNAME}
      - POSTGRES_PASSWORD=${CHAT_DB_PASSWORD}
      - POSTGRES_DB=${CHAT_DB_DATABASE}
    ports:
      - "5438:5432"
    volumes:
      - planner-chat-data:/var/lib/postgresql/data