version: '3.8'

services:
  planer-email-service:
    image: planer-email-service
    restart: always
    ports:
      - "5000:80"
    environment:
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - EMAIL_SENDER_EMAIL=${EMAIL_SENDER_EMAIL}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
      
      - AUTH_SERVICE_BASE_URL=${AUTH_SERVICE_BASE_URL}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}