version: '3.8'

services:
  planner-file-server:
    image: planner-file-server
    restart: always
    ports:
      - "8091:80"
    depends_on:
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PROFILE_IMAGE_QUEUE_NAME=${RABBITMQ_PROFILE_IMAGE_QUEUE_NAME}
      - RABBITMQ_CHAT_IMAGE_QUEUE_NAME=${RABBITMQ_CHAT_IMAGE_QUEUE_NAME}
      - RABBITMQ_CHAT_ATTACHMENT_QUEUE_NAME=${RABBITMQ_CHAT_ATTACHMENT_QUEUE_NAME}

      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - FILE_SERVER_STORAGE_PATH=${FILE_SERVER_STORAGE_PATH}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    volumes:
      - planner-file-server-data:${FILE_SERVER_STORAGE_PATH}