version: '3.8'

services:
  planner-mail-credentials-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${MAIL_CREDENTIALS_DB_USERNAME}
      - POSTGRES_PASSWORD=${MAIL_CREDENTIALS_DB_PASSWORD}
      - POSTGRES_DB=${MAIL_CREDENTIALS_DB_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - planner-mail-credentials-data:/var/lib/postgresql/data