version: '3.8'

services:
  planner-node-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${NODE_DB_USERNAME}
      - POSTGRES_PASSWORD=${NODE_DB_PASSWORD}
      - POSTGRES_DB=${NODE_DB_DATABASE}
    ports:
      - "5439:5432"
    volumes:
      - planner-content-data:/var/lib/postgresql/data