version: '3.8'

services:
  planner-node:
    image: planner-node-service
    restart: always
    ports:
      - "8093:80"
    depends_on:
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - NODE_DB_CONNECTION_STRING=Host=${NODE_DB_HOST};Port=5432;Database=${NODE_DB_DATABASE};Username=${NODE_DB_USERNAME};Password=${NODE_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE=${RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE}
      - RABBITMQ_CREATE_PERSONAL_CHAT_QUEUE=${RABBITMQ_CREATE_PERSONAL_CHAT_QUEUE}

      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      