version: '3.8'

services:
  planner-notify-service:
    image: planner-notify-service
    restart: always
    ports:
      - "8092:80"
    depends_on:
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE=${RABBITMQ_MESSAGE_SENT_TO_CHAT_QUEUE}
      