version: '3.8'

services:
  planner-notify-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${NOTIFY_DB_USERNAME}
      - POSTGRES_PASSWORD=${NOTIFY_DB_PASSWORD}
      - POSTGRES_DB=${NOTIFY_DB_DATABASE}
    ports:
      - "5437:5432"
    volumes:
      - planner-notify-data:/var/lib/postgresql      