version: '3.8'

services:
  planner-task-board:
    image: planner-task-board
    restart: always
    ports:
      - "8889:80"
    depends_on:
      planner-task-board-db:
        condition: service_started
      planner-rabbitmq-service:
        condition: service_healthy
    environment:
      - CONTENT_DB_CONNECTION_STRING=Host=${CONTENT_DB_HOST};Port=5432;Database=${CONTENT_DB_DATABASE};Username=${CONTENT_DB_USERNAME};Password=${CONTENT_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_CREATE_TASK_CHAT_QUEUE=${RABBITMQ_CREATE_TASK_CHAT_QUEUE_NAME}
      - RABBITMQ_CREATE_TASK_CHAT_RESPONSE_QUEUE=${RABBITMQ_CREATE_TASK_CHAT_RESPONSE_QUEUE}
      - RABBITMQ_CHAT_ADD_ACCOUNTS_TO_TASK_CHATS_QUEUE_NAME=${RABBITMQ_CHAT_ADD_ACCOUNTS_TO_TASK_CHATS_QUEUE_NAME}