FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

COPY ../NuGet.config .
COPY ../nuget-local ./nuget-local
COPY . .

RUN dotnet restore planner-auth-service/planner_auth_service.sln
RUN dotnet publish \
  planner-auth-service/src/planner_auth_service.Api/planner_auth_service.Api.csproj \
  -c Release -o /App/out


FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
COPY local.pfx /https/local.pfx
ENTRYPOINT ["dotnet", "planner_auth_service.Api.dll"]