FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

COPY . ./
RUN dotnet restore src/planner-node-service.Api/planner-node-service.Api.csproj
RUN dotnet publish src/planner-node-service.Api/planner-node-service.Api.csproj \
    -c Debug -o /App/out


FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "planner-node-service.Api.dll"]