FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

COPY ../NuGet.config .
COPY ../nuget-local ./nuget-local
COPY . .

RUN dotnet restore planner-chat-server/planner-chat-server.sln

RUN dotnet publish \
  planner-chat-server/src/planner-chat-server.Api/planner-chat-server.Api.csproj \
  -c Release -o /App/out


FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "Planner-chat-server.Api.dll"]