FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY NuGet.config ./
COPY nuget-local ./nuget-local

COPY planner-content-service/planner_content_service.sln ./

COPY planner-content-service/src/planner_content_service.Core/*.csproj src/planner_content_service.Core/
COPY planner-content-service/src/planner_content_service.App/*.csproj src/planner_content_service.App/
COPY planner-content-service/src/planner_content_service.Infrastructure/*.csproj src/planner_content_service.Infrastructure/
COPY planner-content-service/src/planner_content_service.Api/*.csproj src/planner_content_service.Api/

RUN dotnet restore planner_content_service.sln

COPY planner-content-service/src ./src

RUN dotnet build src/planner_content_service.Api/planner_content_service.Api.csproj \
  -c Release --no-restore

RUN dotnet publish src/planner_content_service.Api/planner_content_service.Api.csproj \
  -c Release \
  -o /app/out \
  --no-build \
  /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "planner_content_service.Api.dll"]