// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_content_service.Infrastructure.Data;

#nullable disable

namespace planner_content_service.Api.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260209120542_deleteStatuses")]
    partial class deleteStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Board", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Column", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.ToTable("Columns", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.TaskModel", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HexColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Board", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Board", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Column", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Column", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.TaskModel", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.TaskModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
