// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_content_service.Infrastructure.Data;

#nullable disable

namespace planner_content_service.Api.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.AttachedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttachedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "MessageId")
                        .IsUnique();

                    b.ToTable("AttachedMessages", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.ReadState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReadAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ReadStates", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.UserTaskColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("UserTaskColumns", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Board", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Column", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.ToTable("Columns", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Job", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Node");

                    b.Property<bool>("CloseWhenChildrenCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HexColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimarySourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasIndex("EndDate");

                    b.HasIndex("PrimarySourceMessageId");

                    b.HasIndex("StartDate");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Information", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Job");

                    b.ToTable("Information", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Meeting", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Job");

                    b.Property<DateTime>("MeetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MemberIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasIndex("MeetAt");

                    b.ToTable("Meetings", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Reminder", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Job");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasIndex("RemindAt");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Task", b =>
                {
                    b.HasBaseType("planner_content_service.Core.Entities.Models.Job");

                    b.Property<string>("PerformerIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.AttachedMessage", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Job", "Job")
                        .WithMany("AttachedMessages")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.UserTaskColumn", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Board", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Board", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Column", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Column", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Job", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Job", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_content_service.Core.Entities.Models.AttachedMessage", "PrimarySourceMessage")
                        .WithMany()
                        .HasForeignKey("PrimarySourceMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PrimarySourceMessage");
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Information", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Job", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Information", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Meeting", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Job", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Meeting", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Reminder", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Job", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Reminder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Task", b =>
                {
                    b.HasOne("planner_content_service.Core.Entities.Models.Job", null)
                        .WithOne()
                        .HasForeignKey("planner_content_service.Core.Entities.Models.Task", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_content_service.Core.Entities.Models.Job", b =>
                {
                    b.Navigation("AttachedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
