// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_chat_service.Infrastructure.Data;

#nullable disable

namespace planner_chat_service.Api.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20251226123237_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessGroup");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.ToTable("AccessGroupMember");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("AccountId");

                    b.HasIndex("NodeId");

                    b.HasIndex("AccountId", "NodeId", "AccessType")
                        .IsUnique();

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccountChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateLastViewing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatSettingId");

                    b.HasIndex("SessionId");

                    b.ToTable("AccountChatSessions");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChatName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateLastViewing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageDraft")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatSettings");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Histories_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Histories_CreatedBy");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_Histories_NodeId");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("IX_Histories_UpdatedBy");

                    b.HasIndex("CreatedAt", "NodeId")
                        .HasDatabaseName("IX_Histories_CreatedAt_NodeId");

                    b.HasIndex("NodeId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Histories_NodeId_CreatedAt");

                    b.ToTable("Histories", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("Chat Message");

                    b.Property<string>("Props")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RelationType");

                    b.HasIndex("ParentId", "ChildId", "RelationType")
                        .IsUnique();

                    b.ToTable("NodeLinks");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.HasBaseType("planner_chat_service.Core.Entities.Models.Node");

                    b.Property<int>("ChatType")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatMessage", b =>
                {
                    b.HasBaseType("planner_chat_service.Core.Entities.Models.Node");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasBeenRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasIndex("ChatId");

                    b.HasIndex("HasBeenRead")
                        .HasDatabaseName("IX_ChatMessages_HasBeenRead");

                    b.HasIndex("MessageType")
                        .HasDatabaseName("IX_ChatMessages_MessageType");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessages_SenderId");

                    b.HasIndex("SentAt")
                        .IsDescending()
                        .HasDatabaseName("IX_ChatMessages_SentAt");

                    b.HasIndex("SenderId", "HasBeenRead", "SentAt")
                        .HasDatabaseName("IX_ChatMessages_SenderId_HasBeenRead_SentAt");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessGroupMember", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.AccessGroup", "AccessGroup")
                        .WithMany("Members")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessRight", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.AccessGroup", "AccessGroup")
                        .WithMany()
                        .HasForeignKey("AccessGroupId");

                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccountChatSession", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.ChatSettings", "ChatSetting")
                        .WithMany("UserChatSessions")
                        .HasForeignKey("ChatSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSetting");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithMany("ChatMemberships")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.History", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_chat_service.Core.Entities.Models.Chat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatMessage", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId");

                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_chat_service.Core.Entities.Models.ChatMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccessGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.Navigation("UserChatSessions");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.Navigation("ChatMemberships");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
