// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_chat_service.Infrastructure.Data;

#nullable disable

namespace planner_chat_service.Api.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260331105934_chatEditedAt")]
    partial class chatEditedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccountChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateLastViewing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatSettingId");

                    b.HasIndex("SessionId");

                    b.ToTable("AccountChatSessions");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatEdit", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Seq");

                    b.HasIndex("ChatId");

                    b.HasIndex("MessageId");

                    b.ToTable("ChatEdits");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChatName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateLastViewing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageDraft")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatSettings");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatState", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<long>("EditCursorId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastMessageSeq")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("LastPreview", "planner_chat_service.Core.Entities.Models.ChatState.LastPreview#MessagePreview", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("SentAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("ChatId");

                    b.HasIndex("EditCursorId");

                    b.ToTable("ChatStates", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatUserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("CachedUnreadCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastReadSeq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatUserStates", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("Chat Message");

                    b.Property<string>("Props")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.UserHiddenMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId", "AccountId");

                    b.ToTable("UserHiddenMessages");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.HasBaseType("planner_chat_service.Core.Entities.Models.Node");

                    b.Property<int>("ChatType")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatMessage", b =>
                {
                    b.HasBaseType("planner_chat_service.Core.Entities.Models.Node");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasBeenRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SenderDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasIndex("ChatId");

                    b.HasIndex("HasBeenRead")
                        .HasDatabaseName("IX_ChatMessages_HasBeenRead");

                    b.HasIndex("MessageType")
                        .HasDatabaseName("IX_ChatMessages_MessageType");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessages_SenderId");

                    b.HasIndex("SentAt")
                        .IsDescending()
                        .HasDatabaseName("IX_ChatMessages_SentAt");

                    b.HasIndex("SenderId", "HasBeenRead", "SentAt")
                        .HasDatabaseName("IX_ChatMessages_SenderId_HasBeenRead_SentAt");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.AccountChatSession", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.ChatSettings", "ChatSetting")
                        .WithMany("UserChatSessions")
                        .HasForeignKey("ChatSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSetting");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatEdit", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_chat_service.Core.Entities.Models.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithMany("ChatMemberships")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatState", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithOne()
                        .HasForeignKey("planner_chat_service.Core.Entities.Models.ChatState", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_chat_service.Core.Entities.Models.ChatEdit", "EditCursor")
                        .WithMany()
                        .HasForeignKey("EditCursorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chat");

                    b.Navigation("EditCursor");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatUserState", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.UserHiddenMessage", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_chat_service.Core.Entities.Models.Chat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatMessage", b =>
                {
                    b.HasOne("planner_chat_service.Core.Entities.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("planner_chat_service.Core.Entities.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("planner_chat_service.Core.Entities.Models.ChatMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.ChatSettings", b =>
                {
                    b.Navigation("UserChatSessions");
                });

            modelBuilder.Entity("planner_chat_service.Core.Entities.Models.Chat", b =>
                {
                    b.Navigation("ChatMemberships");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
