FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

COPY ../NuGet.config .
COPY ../nuget-local ./nuget-local
COPY . .

RUN dotnet restore planner-file-service/planner_file_service.sln
RUN dotnet publish \
  planner-file-service/src/planner_file_service.Api/planner_file_service.Api.csproj \
  -c Release -o /App/out

# Финальный образ
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App

ENV FILE_SERVER_STORAGE_PATH=/file-storage

RUN mkdir -p ${FILE_SERVER_STORAGE_PATH}

COPY --from=build-env /App/out .

# Копируем всю папку themes в директорию хранения
COPY planner-file-service/themes/ ${FILE_SERVER_STORAGE_PATH}/

ENTRYPOINT ["dotnet", "planner_file_service.Api.dll"]