FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

COPY ../NuGet.config .
COPY ../nuget-local ./nuget-local

COPY planner-notify-service/*.sln .
COPY planner-notify-service/src/planner_notify_service.Api/*.csproj ./src/

RUN dotnet restore ./planner-notify-service/planner_notify_service.sln

COPY planner-notify-service ./planner-notify-service	

RUN dotnet publish \
  planner-notify-service/src/planner_notify_service.Api/planner_notify_service.Api.csproj \
  -c Release \
  -o /App/out \
  --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "planner_notify_service.Api.dll"]