namespace planner_server_package.Events.Enums
{
    public enum PublishEvent
    {
        AccountCreated,
        UpdateProfileImage,
        UpdateChatImage,
        ScopeUpdated,
        SentFileToChat,
        CreatePersonalChat,
        GetNotificationSettings,
        AddAccountToChat,
        ResponseTaskChat,
        MessageSentToChat,
        InitChat,
        CreateAccountMailCredentials,
        AddAccountsToTaskChats,
        ContentNodes,
        ChatNodes,
        CreateBoard,
        CreateColumn,
        CreateTask,
        DeleteNode,
        CheckAccess,
        AccessRevoked,
        SendNotification,
        GetGoogleToken
    }
}