// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_server_package.Idempotency;

#nullable disable

namespace planner_content_service.Api.Migrations.Idempotency
{
    [DbContext(typeof(IdempotencyContext))]
    [Migration("20260330122014_InitialIdempotency")]
    partial class InitialIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_server_package.Idempotency.OperationFailure", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("OperationName")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("OperationId");

                    b.ToTable("OperationFailures");
                });

            modelBuilder.Entity("planner_server_package.Idempotency.ProcessOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationName")
                        .HasColumnType("integer");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.ToTable("ProcessedOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
