// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_node_service.Infrastructure.Data;

#nullable disable

namespace planner_node_service.Api.Migrations
{
    [DbContext(typeof(NodeDbContext))]
    [Migration("20260204092142_DeleteCreatedAtByFromStatusHistory")]
    partial class DeleteCreatedAtByFromStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.ToTable("AccessGroupMembers");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("TrackableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_Histories_ActorId");

                    b.HasIndex("TrackableId")
                        .HasDatabaseName("IX_Histories_TrackableId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Statuses");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("StatusId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.TrackableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Trackables");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.PublicationStatusModel", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.StatusBase");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ToTable("PublicationStatuses", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.WorkflowStatusModel", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.StatusBase");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ToTable("WorkflowStatuses", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessGroup", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.TrackableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("AccessGroups");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessRight", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.TrackableEntity");

                    b.Property<Guid?>("AccessGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("AccountId");

                    b.HasIndex("NodeId");

                    b.HasIndex("AccountId", "NodeId", "AccessType")
                        .IsUnique();

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.Node", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.TrackableEntity");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.TrackableEntity");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RelationType");

                    b.HasIndex("ParentId", "ChildId", "RelationType")
                        .IsUnique();

                    b.ToTable("NodeLinks", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessGroupMember", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.AccessGroup", "AccessGroup")
                        .WithMany("Members")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.History", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.TrackableEntity", "Trackable")
                        .WithMany()
                        .HasForeignKey("TrackableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trackable");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusBase", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusHistory", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.StatusBase", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.PublicationStatusModel", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.StatusBase", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.PublicationStatusModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.WorkflowStatusModel", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.StatusBase", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.WorkflowStatusModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessGroup", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.TrackableEntity", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.AccessGroup", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessRight", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.AccessGroup", "AccessGroup")
                        .WithMany()
                        .HasForeignKey("AccessGroupId");

                    b.HasOne("planner_node_service.Core.Entities.Models.TrackableEntity", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.AccessRight", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.Node", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.TrackableEntity", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.Node", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.TrackableEntity", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.NodeLink", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
