// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using planner_node_service.Infrastructure.Data;

#nullable disable

namespace planner_node_service.Api.Migrations
{
    [DbContext(typeof(NodeDbContext))]
    [Migration("20260413052314_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessLog", b =>
                {
                    b.Property<int>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Seq"));

                    b.Property<long>("GraphRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<long>("RulesRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Seq");

                    b.HasIndex("ScopeId");

                    b.ToTable("AccessLogs", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "NodeId", "Permission")
                        .IsUnique();

                    b.ToTable("AccessRules");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AccessSubjects");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.ContentLog", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<long>("ScopeVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Seq");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_ContentLogs_EntityId");

                    b.ToTable("ContentLogs", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "AccountId")
                        .IsUnique();

                    b.ToTable("AccessGroupMembers");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("NewVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OldVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_Histories_NodeId");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("IX_Histories_UpdatedById");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Props")
                        .HasColumnType("jsonb");

                    b.Property<int>("SyncKind")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RelationType");

                    b.HasIndex("ParentId", "ChildId", "RelationType")
                        .IsUnique();

                    b.ToTable("NodeLinks", (string)null);
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("IX_Status_NodeId_Kind");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OldStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.SyncScopeAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("GraphRevisionUsed")
                        .HasColumnType("bigint");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<long>("RulesRevisionUsed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "AccountId")
                        .IsUnique();

                    b.ToTable("SyncScopeAccess");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.GroupAccessSubject", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.AccessSubject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GroupAccessSubjects");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.UserAccessSubject", b =>
                {
                    b.HasBaseType("planner_node_service.Core.Entities.Models.AccessSubject");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("UserAccessSubjects");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessLog", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.AccessRule", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.AccessSubject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.GroupMember", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.GroupAccessSubject", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NodeLink", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.NotificationSettings", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.Status", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.StatusHistory", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Status", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planner_node_service.Core.Entities.Models.Status", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.SyncScopeAccess", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.Node", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.GroupAccessSubject", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.AccessSubject", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.GroupAccessSubject", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.UserAccessSubject", b =>
                {
                    b.HasOne("planner_node_service.Core.Entities.Models.AccessSubject", null)
                        .WithOne()
                        .HasForeignKey("planner_node_service.Core.Entities.Models.UserAccessSubject", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planner_node_service.Core.Entities.Models.GroupAccessSubject", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
